version: '3.9'

services:
  casa:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"